# -*- coding: utf-8 -*-
"""
/***************************************************************************
 japanGeology3
                                 A QGIS plugin
 japanGeology3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-12
        copyright            : (C) 2023 by nirmal
        email                : joshi.nirmalraj@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load japanGeology3 class from file japanGeology3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .japanGeology3 import japanGeology3
    return japanGeology3(iface)
